### ISSUE TITLE
Missing OmniVirt?

### ISSUE THREAD

**Issue by rooskienz** [OmniVirt/OmniVirtAdNetwork-Unity-Example#2] opened 2017-07-06 10:33 UTC
Hi,
I've downloaded the package, installed it and right after that I get this error:

`Assets/Omnivirt SDK Demo/Scripts/AdNetworkController.cs(5,7): error CS0246: The type or namespace name OmniVirt could not be found. Are you missing an assembly reference?`

I can't seem to be able to find the namespace `OmniVirt` anywhere in the project and no `VRAd` class. Are they missing or are they in one of the dlls?

**Comment by baddth** [comment] 2017-07-10 05:46
Hi rooskienz,

I checked out the Ad Network Example scene and can run without problem. I also tried download the framework and import it into the new project using the instruction in README and couldn't reproduce the issue.

To isolate the issue, can you try our example scene first? I selected the Build export to iPhone and everything look straightforward. Maybe, can you let me know your configuration so that we can reproduce it with your setting?

Best,
Brad

**Comment by baddth** [comment] 2017-07-12 20:14
Hi rooskienz,

Thank you for the example project. We have reviewed the project structure and it seems like there was some issue during asset importing process which let VRKit.dll unusable. To fix this problem, please browse to file Assets -> Plugins -> VRKit in Project pane and make sure that Editor, iOS and Android are all checked in Inspector pane like image below. And everything should work like a charm now.

Screenshot: [https://raw.githubusercontent.com/OmniVirt/OmniVirtAdNetwork-Unity-Example/master/Screenshots/vrkitplatforms.jpg](https://raw.githubusercontent.com/OmniVirt/OmniVirtAdNetwork-Unity-Example/master/Screenshots/vrkitplatforms.jpg)

We also updated our setup instruction on our Github. If you still find problem, please let us know. We can reactivate the ticket and continue looking for you.

Thanks,
Brad

**Closed as completed by baddth** 2017-07-12 20:14 UTC
